language: node_js
node_js: "16"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: "G8xOOqf7kDq8YoWeYE8ZntykoVhMfQQaZNAlbT+wdl7ULzRU/45NNsAadykb3U4QBwkOQwa0IIZTDWuxX7AyFmIhrGdLZElI8O8QYH5JNwlV01gAT7cF2H/O+5YnVyCVTQQ2MvCDEWMwJEbxoQf2qId/TPFAs4+uBsQ/KAha99GLD3RhYADo04bS2nXuyv5XcTnFdnp7mGNwtCsRI6B3Bwi3R+fqTfRhLr0CNzWgf7Q3IL92/6ScF7YuW0CWruLyQFDxuLxxD25FIpR8W7NhrMpZ3GexrIDWdiupjJUzytlX1FAuEpuVsGSsOgtifg3dKKUyh3Ae9BgRXBcpDfJAbKTtgTISYlH52ku0ttQYeTnjosROUBIIC5jfbZgsG5gWL3mF491bU8YpUczZ2uk9x3Qo7VplCrOfbPCrTnJBommVFMocnV6IZrRljgY+IdFI1RlkEj9VztygdJ/VwzZ65sk++AAWmRg1gxA9NUGlQucot2JxAG7r6TM32y1ipfdEHHpcisPdYC3NpmNM/uTK0AZnTcVUzz4eWF3J2D60oq6b1aer9Q2mh1bXomcrbSPiV7nMLqPNnkU+Yq4Zib85aRLxvLGM7CilGbNUKFBvR5DndMV9V4uhXXJS9djMyr0hfHKIl+6Ob/2KE6jsS569bUBspH6QyIo8XDcvUNmOIjQ="

services: docker

osx_image: xcode14.2
dist: jammy

matrix:
  include:
    - os: osx
    - os: linux

cache:
  directories:
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      # Clear TRAVIS_CMD as it will be multi-line which breaks --env-file
      export TRAVIS_CMD=
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm run release -- --windows --linux"
    else
      npm run release
    fi

deploy:
  provider: npm
  email: npm@xuluwarrior.org
  api_key:
    secure: p2bV4gvv1lCRHXnxega4kDRQruZnXzdjhPL6DuR5yrgvZN5gJwu/sH10yQY8xnziSUqbRLqGWQymCGFseuXvpnvtja6UvreCjAhO+ZdN5FxGVZcEy4MMVxZ1+2N4L8zzMoRsirg6t2Bogn4x61/lQBpDRIMvtg8i8GlmmiuYvWX7Z7hxgL0tLYlGPvrtqn3i2HbwvHhZh+K2HGxPEO33YozYfisfUhQKWdtQoc9jJ6SMpPIMnSuswrE2ezVIDO0fJ5y8InEChBTZXPdLAiSENzW83gEvYE61nDVG/T8x2YWrJW6oiiR5Uh9lPVumPiB+GdRsJv2vg/8v+hIeSWhgf2wT/y6WCx6/9vL6pK+TTbTg4GukBleLo7fl0SWj146hIO8P3cC1GlXGfob4gj51RNLtjXiZ4B3gLpSxI7i5nFxSIK+h5vfqagAng1koL1EpZuBe1pDCqyTpN8Uk7LAsoA0ov40bgcVGjXBxG4rbEYXA5kcNh6F4hC/IhjSjC7kNQU5YqpUj7OGDaYTcyDRkebbog8aLgQsZ1ISVGOLujJM1VAjgEnxsMHOqWSu27EUCzltVXhzSlCWjs5fuUJ7syUAns+QkylO7ljvS5+vXr3N4G3LZwvhhX4vxrZDULfrZUczifEggo5f6zF09idffdDqyL51whyM6WpPhYSs5DVc=
  on:
    tags: true
    repo: XuluWarrior/swagger-editor-offline
#deploy:
#  provider: releases
#  api_key:
#    secure: "BKW5wqAx5i0T7Jg88kCu8jLfk8zhEyG5hcojs6Ex5L0VJNFYiJoOsy3CiuwgvDum/Z3D8SSBHKKTj44BUlRLqj5Mjz9IZooR4PXhexNMx/BOJN8+mwDNtTA/KSlVA/HKKgZB4jC+TCn3YO2Tv1bd0hVgkrbcZG8Ed8PQSRzrKvanSY5sIiBi4jPUezT64k1+TPlMZc8CyrBvHEa8f51Spj1CwFMPp66QKW5PZqsGNnNR8nydltEwwakLyc93Z0nfPLzXG9ZoSpBfUr8XVxmTR/Uxe5/cTy/8T/z6OoMB4GudruOWfUv48RLOO13uEdqaqtB7/kT0VM6YnKD60+2VApp3EZBmSL2RVNyjY1ThZPSRmp41w8G7T47niYxQiA+BrKWXPW9Tfw/RLFkiIVPss4yvlJF+z7Wj+CtvPJSu6OlrelhM4qzmwpCcu97sNevC491xc5595Ugmg7W50j6cymkTxM/bpjqCUutKhRGlU+zTLgBv36SQGKMJqFsEYa27WuQcICy27cZEJb76VPOpZuz6BnENUPGW3fv/yU54DoP+onwAcd2kO3k0lBCdfV4j662fRjALw5kaVtlMg1yn+KTFW6e5MFPPVwz7m41g6hq6SWw3uxbdYiU7O6yGpP7otf6m2CyEslD8CaPcaoCWYJcKYsCAQ3xq39ysJkJcS1g="
#  file_glob: true
#  file: electron/dist/*.*
#  skip_cleanup: true
#  on:
#    tags: true

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

#branches:
#  except:
#    - "/^v\\d+\\.\\d+\\.\\d+$/"